AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 3
Resources:
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lijs-aws-serverless-api-intro/lijs-aws-serverless-api-intro-dev/f23d950bae6cba2628d2793be7ed9299
      Handler: getUser.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          USER_TABLE_NAME: User
      Policies:
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:BatchGetItem
          - dynamodb:GetItem
          Resource:
            Fn::GetAtt:
            - UserTable
            - Arn
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /{user_id}
            Method: get
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: User
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
