AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        USER_TABLE_NAME: User
Resources:
  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lijs-aws-serverless-api-intro/lijs-aws-serverless-api-intro-dev/310d56a9cba5f2e113019e47880b7691
      Handler: getUser.handler
      Runtime: nodejs8.10
      Events:
        GetUsersEndpoint:
          Type: Api
          Properties:
            Path: /user
            Method: get
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:BatchGetItem
          - dynamodb:GetItem
          Resource:
            Fn::GetAtt:
            - UserTable
            - Arn
  SaveUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lijs-aws-serverless-api-intro/lijs-aws-serverless-api-intro-dev/310d56a9cba5f2e113019e47880b7691
      Handler: saveUser.handler
      Runtime: nodejs8.10
      Events:
        SaveUsersEndpoint:
          Type: Api
          Properties:
            Path: /user
            Method: post
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:PutItem
          Resource:
            Fn::GetAtt:
            - UserTable
            - Arn
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: User
      AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
